Search.appendIndex(
    [
                {
            "fqsen": "\\swentel\\nostr\\Application\\Client",
            "name": "Client",
            "summary": "",
            "url": "classes/swentel-nostr-Application-Client.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Application\\Client\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020Nostr\u0020Client.",
            "url": "classes/swentel-nostr-Application-Client.html#method_run"
        },                {
            "fqsen": "\\swentel\\nostr\\Application\\Client\u003A\u003AshowHelp\u0028\u0029",
            "name": "showHelp",
            "summary": "",
            "url": "classes/swentel-nostr-Application-Client.html#method_showHelp"
        },                {
            "fqsen": "\\swentel\\nostr\\CommandResultInterface",
            "name": "CommandResultInterface",
            "summary": "",
            "url": "classes/swentel-nostr-CommandResultInterface.html"
        },                {
            "fqsen": "\\swentel\\nostr\\CommandResultInterface\u003A\u003AisSuccess\u0028\u0029",
            "name": "isSuccess",
            "summary": "Returns\u0020whether\u0020the\u0020request\u0020was\u0020successful.",
            "url": "classes/swentel-nostr-CommandResultInterface.html#method_isSuccess"
        },                {
            "fqsen": "\\swentel\\nostr\\CommandResultInterface\u003A\u003Amessage\u0028\u0029",
            "name": "message",
            "summary": "Returns\u0020the\u0020message,\u0020if\u0020any.",
            "url": "classes/swentel-nostr-CommandResultInterface.html#method_message"
        },                {
            "fqsen": "\\swentel\\nostr\\CommandResultInterface\u003A\u003AgetEventId\u0028\u0029",
            "name": "getEventId",
            "summary": "Returns\u0020the\u0020event\u0020id.",
            "url": "classes/swentel-nostr-CommandResultInterface.html#method_getEventId"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event",
            "name": "Event",
            "summary": "Generic\u0020Nostr\u0020event\u0020class.",
            "url": "classes/swentel-nostr-Event-Event.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Base\u0020constructor\u0020for\u0020events.",
            "url": "classes/swentel-nostr-Event-Event.html#method___construct"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Set\u0020the\u0020event\u0020id.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setId"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Get\u0020the\u0020event\u0020id.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getId"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetPublicKey\u0028\u0029",
            "name": "setPublicKey",
            "summary": "Set\u0020the\u0020public\u0020key.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setPublicKey"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetPublicKey\u0028\u0029",
            "name": "getPublicKey",
            "summary": "Get\u0020the\u0020public\u0020key.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getPublicKey"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetSignature\u0028\u0029",
            "name": "setSignature",
            "summary": "Set\u0020the\u0020signature.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setSignature"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetSignature\u0028\u0029",
            "name": "getSignature",
            "summary": "Get\u0020the\u0020signature.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getSignature"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetKind\u0028\u0029",
            "name": "setKind",
            "summary": "Set\u0020the\u0020event\u0020kind.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setKind"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetKind\u0028\u0029",
            "name": "getKind",
            "summary": "Returns\u0020the\u0020kind.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getKind"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Set\u0020the\u0020event\u0020content.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setContent"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Get\u0020the\u0020event\u0020content.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getContent"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetTags\u0028\u0029",
            "name": "setTags",
            "summary": "Set\u0020the\u0020event\u0020tags\u0020with\u0020values.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setTags"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AaddTag\u0028\u0029",
            "name": "addTag",
            "summary": "Add\u0020a\u0020single\u0020tag\u0020to\u0020the\u0020event.",
            "url": "classes/swentel-nostr-Event-Event.html#method_addTag"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "Get\u0020the\u0020event\u0020tags.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getTags"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "Set\u0020the\u0020event\u0020created\u0020time.",
            "url": "classes/swentel-nostr-Event-Event.html#method_setCreatedAt"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "Get\u0020the\u0020event\u0020created\u0020time.",
            "url": "classes/swentel-nostr-Event-Event.html#method_getCreatedAt"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Convert\u0020the\u0020object\u0020to\u0020an\u0020array.",
            "url": "classes/swentel-nostr-Event-Event.html#method_toArray"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "Convert\u0020the\u0020event\u0020object\u0020to\u0020a\u0020JSON\u0020string.",
            "url": "classes/swentel-nostr-Event-Event.html#method_toJson"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "Returns\u0020true\u0020if\u0020event\u0020object\u0020encodes\u0020to\u0020a\u0020valid\u0020Nostr\u0020event\u0020JSON\u0020string.",
            "url": "classes/swentel-nostr-Event-Event.html#method_verify"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024kind",
            "name": "kind",
            "summary": "The\u0020event\u0020kind\u0020which\u0020is\u0020an\u0020integer\u0020between\u00200\u0020and\u002065535.",
            "url": "classes/swentel-nostr-Event-Event.html#property_kind"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024id",
            "name": "id",
            "summary": "The\u0020event\u0020id.",
            "url": "classes/swentel-nostr-Event-Event.html#property_id"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024sig",
            "name": "sig",
            "summary": "The\u0020event\u0020signature.",
            "url": "classes/swentel-nostr-Event-Event.html#property_sig"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024pubkey",
            "name": "pubkey",
            "summary": "32\u002Dbytes\u0020lowercase\u0020hex\u002Dencoded\u0020public\u0020key\u0020of\u0020the\u0020event\u0020creator.",
            "url": "classes/swentel-nostr-Event-Event.html#property_pubkey"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024content",
            "name": "content",
            "summary": "The\u0020event\u0020content.",
            "url": "classes/swentel-nostr-Event-Event.html#property_content"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024created_at",
            "name": "created_at",
            "summary": "The\u0020created\u0020at\u0020unix\u0020timestamp\u0020in\u0020seconds.",
            "url": "classes/swentel-nostr-Event-Event.html#property_created_at"
        },                {
            "fqsen": "\\swentel\\nostr\\Event\\Event\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "Tags\u0020of\u0020the\u0020event.",
            "url": "classes/swentel-nostr-Event-Event.html#property_tags"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface",
            "name": "EventInterface",
            "summary": "Nostr\u0020Event\u0020interface.",
            "url": "classes/swentel-nostr-EventInterface.html"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Set\u0020the\u0020event\u0020id.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setId"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Get\u0020the\u0020event\u0020id.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getId"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetSignature\u0028\u0029",
            "name": "setSignature",
            "summary": "Set\u0020the\u0020signature.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setSignature"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetSignature\u0028\u0029",
            "name": "getSignature",
            "summary": "Get\u0020the\u0020signature.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getSignature"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetPublicKey\u0028\u0029",
            "name": "setPublicKey",
            "summary": "Set\u0020the\u0020public\u0020key.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setPublicKey"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetPublicKey\u0028\u0029",
            "name": "getPublicKey",
            "summary": "Get\u0020the\u0020public\u0020key.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getPublicKey"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetKind\u0028\u0029",
            "name": "setKind",
            "summary": "Set\u0020the\u0020event\u0020kind.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setKind"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetKind\u0028\u0029",
            "name": "getKind",
            "summary": "Returns\u0020the\u0020kind.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getKind"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Set\u0020the\u0020event\u0020content.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setContent"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Get\u0020the\u0020event\u0020content.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getContent"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "Set\u0020the\u0020event\u0020created\u0020time.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setCreatedAt"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "Get\u0020the\u0020event\u0020created\u0020time.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getCreatedAt"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AsetTags\u0028\u0029",
            "name": "setTags",
            "summary": "Set\u0020the\u0020event\u0020tags\u0020with\u0020values.",
            "url": "classes/swentel-nostr-EventInterface.html#method_setTags"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AaddTag\u0028\u0029",
            "name": "addTag",
            "summary": "Add\u0020a\u0020single\u0020tag\u0020to\u0020the\u0020event.",
            "url": "classes/swentel-nostr-EventInterface.html#method_addTag"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "Get\u0020the\u0020event\u0020tags.",
            "url": "classes/swentel-nostr-EventInterface.html#method_getTags"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Convert\u0020the\u0020object\u0020to\u0020an\u0020array.",
            "url": "classes/swentel-nostr-EventInterface.html#method_toArray"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "Convert\u0020the\u0020event\u0020object\u0020to\u0020a\u0020JSON\u0020string.",
            "url": "classes/swentel-nostr-EventInterface.html#method_toJson"
        },                {
            "fqsen": "\\swentel\\nostr\\EventInterface\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "Returns\u0020true\u0020if\u0020event\u0020object\u0020encodes\u0020to\u0020a\u0020valid\u0020Nostr\u0020event\u0020JSON\u0020string.",
            "url": "classes/swentel-nostr-EventInterface.html#method_verify"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key",
            "name": "Key",
            "summary": "",
            "url": "classes/swentel-nostr-Key-Key.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key\u003A\u003AgeneratePrivateKey\u0028\u0029",
            "name": "generatePrivateKey",
            "summary": "Generate\u0020private\u0020key\u0020as\u0020hex.",
            "url": "classes/swentel-nostr-Key-Key.html#method_generatePrivateKey"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key\u003A\u003AgetPublicKey\u0028\u0029",
            "name": "getPublicKey",
            "summary": "Generate\u0020public\u0020key\u0020from\u0020private\u0020key\u0020as\u0020hex.",
            "url": "classes/swentel-nostr-Key-Key.html#method_getPublicKey"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key\u003A\u003AconvertToHex\u0028\u0029",
            "name": "convertToHex",
            "summary": "Convert\u0020a\u0020key\u0020to\u0020hex.",
            "url": "classes/swentel-nostr-Key-Key.html#method_convertToHex"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key\u003A\u003AconvertPublicKeyToBech32\u0028\u0029",
            "name": "convertPublicKeyToBech32",
            "summary": "Convert\u0020a\u0020public\u0020hex\u0020key\u0020to\u0020bech32.",
            "url": "classes/swentel-nostr-Key-Key.html#method_convertPublicKeyToBech32"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key\u003A\u003AconvertPrivateKeyToBech32\u0028\u0029",
            "name": "convertPrivateKeyToBech32",
            "summary": "Convert\u0020a\u0020private\u0020hex\u0020key\u0020to\u0020bech32.",
            "url": "classes/swentel-nostr-Key-Key.html#method_convertPrivateKeyToBech32"
        },                {
            "fqsen": "\\swentel\\nostr\\Key\\Key\u003A\u003AconvertToBech32\u0028\u0029",
            "name": "convertToBech32",
            "summary": "Convert\u0020a\u0020hex\u0020key\u0020to\u0020bech32.",
            "url": "classes/swentel-nostr-Key-Key.html#method_convertToBech32"
        },                {
            "fqsen": "\\swentel\\nostr\\Message\\EventMessage",
            "name": "EventMessage",
            "summary": "",
            "url": "classes/swentel-nostr-Message-EventMessage.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Message\\EventMessage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/swentel-nostr-Message-EventMessage.html#method___construct"
        },                {
            "fqsen": "\\swentel\\nostr\\Message\\EventMessage\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generate\u0020the\u0020message\u0020ready\u0020to\u0020be\u0020sent\u0020to\u0020a\u0020relay.",
            "url": "classes/swentel-nostr-Message-EventMessage.html#method_generate"
        },                {
            "fqsen": "\\swentel\\nostr\\Message\\EventMessage\u003A\u003A\u0024event",
            "name": "event",
            "summary": "The\u0020event.",
            "url": "classes/swentel-nostr-Message-EventMessage.html#property_event"
        },                {
            "fqsen": "\\swentel\\nostr\\MessageInterface",
            "name": "MessageInterface",
            "summary": "",
            "url": "classes/swentel-nostr-MessageInterface.html"
        },                {
            "fqsen": "\\swentel\\nostr\\MessageInterface\u003A\u003Agenerate\u0028\u0029",
            "name": "generate",
            "summary": "Generate\u0020the\u0020message\u0020ready\u0020to\u0020be\u0020sent\u0020to\u0020a\u0020relay.",
            "url": "classes/swentel-nostr-MessageInterface.html#method_generate"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult",
            "name": "CommandResult",
            "summary": "",
            "url": "classes/swentel-nostr-Relay-CommandResult.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020the\u0020Relay\u0020Response.",
            "url": "classes/swentel-nostr-Relay-CommandResult.html#method___construct"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult\u003A\u003AisSuccess\u0028\u0029",
            "name": "isSuccess",
            "summary": "Returns\u0020whether\u0020the\u0020request\u0020was\u0020successful.",
            "url": "classes/swentel-nostr-Relay-CommandResult.html#method_isSuccess"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult\u003A\u003A\u0024message",
            "name": "message",
            "summary": "The\u0020message.",
            "url": "classes/swentel-nostr-Relay-CommandResult.html#property_message"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult\u003A\u003AgetEventId\u0028\u0029",
            "name": "getEventId",
            "summary": "Returns\u0020the\u0020event\u0020id.",
            "url": "classes/swentel-nostr-Relay-CommandResult.html#method_getEventId"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult\u003A\u003A\u0024success",
            "name": "success",
            "summary": "Whether\u0020the\u0020request\u0020was\u0020successful\u0020or\u0020not.",
            "url": "classes/swentel-nostr-Relay-CommandResult.html#property_success"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\CommandResult\u003A\u003A\u0024eventId",
            "name": "eventId",
            "summary": "The\u0020event\u0020ID.",
            "url": "classes/swentel-nostr-Relay-CommandResult.html#property_eventId"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\Relay",
            "name": "Relay",
            "summary": "",
            "url": "classes/swentel-nostr-Relay-Relay.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\Relay\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructs\u0020the\u0020Relay.",
            "url": "classes/swentel-nostr-Relay-Relay.html#method___construct"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\Relay\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "Get\u0020url\u0020of\u0020the\u0020relay.",
            "url": "classes/swentel-nostr-Relay-Relay.html#method_getUrl"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\Relay\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020the\u0020message\u0020to\u0020the\u0020relay.",
            "url": "classes/swentel-nostr-Relay-Relay.html#method_send"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\Relay\u003A\u003A\u0024url",
            "name": "url",
            "summary": "The\u0020relay\u0020URL.",
            "url": "classes/swentel-nostr-Relay-Relay.html#property_url"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay\\Relay\u003A\u003A\u0024payload",
            "name": "payload",
            "summary": "the\u0020payload\u0020to\u0020send.",
            "url": "classes/swentel-nostr-Relay-Relay.html#property_payload"
        },                {
            "fqsen": "\\swentel\\nostr\\RelayInterface",
            "name": "RelayInterface",
            "summary": "",
            "url": "classes/swentel-nostr-RelayInterface.html"
        },                {
            "fqsen": "\\swentel\\nostr\\RelayInterface\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "Get\u0020url\u0020of\u0020the\u0020relay.",
            "url": "classes/swentel-nostr-RelayInterface.html#method_getUrl"
        },                {
            "fqsen": "\\swentel\\nostr\\RelayInterface\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020the\u0020message\u0020to\u0020the\u0020relay.",
            "url": "classes/swentel-nostr-RelayInterface.html#method_send"
        },                {
            "fqsen": "\\swentel\\nostr\\Sign\\Sign",
            "name": "Sign",
            "summary": "",
            "url": "classes/swentel-nostr-Sign-Sign.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Sign\\Sign\u003A\u003AsignEvent\u0028\u0029",
            "name": "signEvent",
            "summary": "Sign\u0020an\u0020event.",
            "url": "classes/swentel-nostr-Sign-Sign.html#method_signEvent"
        },                {
            "fqsen": "\\swentel\\nostr\\Sign\\Sign\u003A\u003AserializeEvent\u0028\u0029",
            "name": "serializeEvent",
            "summary": "Serialize\u0020the\u0020event\u0020so\u0020the\u0020id\u0020can\u0020be\u0020created.",
            "url": "classes/swentel-nostr-Sign-Sign.html#method_serializeEvent"
        },                {
            "fqsen": "\\ConvertTest",
            "name": "ConvertTest",
            "summary": "",
            "url": "classes/ConvertTest.html"
        },                {
            "fqsen": "\\ConvertTest\u003A\u003AtestKeyConversion\u0028\u0029",
            "name": "testKeyConversion",
            "summary": "Tests\u0020key\u0020conversion.",
            "url": "classes/ConvertTest.html#method_testKeyConversion"
        },                {
            "fqsen": "\\GenerateTest",
            "name": "GenerateTest",
            "summary": "",
            "url": "classes/GenerateTest.html"
        },                {
            "fqsen": "\\GenerateTest\u003A\u003AtestGetPublicKey\u0028\u0029",
            "name": "testGetPublicKey",
            "summary": "Tests\u0020getting\u0020public\u0020key\u0020from\u0020private\u0020key.",
            "url": "classes/GenerateTest.html#method_testGetPublicKey"
        },                {
            "fqsen": "\\RelayTest",
            "name": "RelayTest",
            "summary": "",
            "url": "classes/RelayTest.html"
        },                {
            "fqsen": "\\RelayTest\u003A\u003AtestSendNoteToRelay\u0028\u0029",
            "name": "testSendNoteToRelay",
            "summary": "Tests\u0020sending\u0020a\u0020note\u0020to\u0020a\u0020relay.",
            "url": "classes/RelayTest.html#method_testSendNoteToRelay"
        },                {
            "fqsen": "\\SerializeTest",
            "name": "SerializeTest",
            "summary": "",
            "url": "classes/SerializeTest.html"
        },                {
            "fqsen": "\\SerializeTest\u003A\u003AtestSerializeEvent\u0028\u0029",
            "name": "testSerializeEvent",
            "summary": "Tests\u0020serializing\u0020event.",
            "url": "classes/SerializeTest.html#method_testSerializeEvent"
        },                {
            "fqsen": "\\VerifyTest",
            "name": "VerifyTest",
            "summary": "",
            "url": "classes/VerifyTest.html"
        },                {
            "fqsen": "\\VerifyTest\u003A\u003AtestValidEventValidation\u0028\u0029",
            "name": "testValidEventValidation",
            "summary": "",
            "url": "classes/VerifyTest.html#method_testValidEventValidation"
        },                {
            "fqsen": "\\VerifyTest\u003A\u003AtestInvalidEventsValidation\u0028\u0029",
            "name": "testInvalidEventsValidation",
            "summary": "",
            "url": "classes/VerifyTest.html#method_testInvalidEventsValidation"
        },                {
            "fqsen": "\\VerifyTest\u003A\u003AinvalidEventsProvider\u0028\u0029",
            "name": "invalidEventsProvider",
            "summary": "",
            "url": "classes/VerifyTest.html#method_invalidEventsProvider"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Application",
            "name": "Application",
            "summary": "",
            "url": "namespaces/swentel-nostr-application.html"
        },                {
            "fqsen": "\\swentel\\nostr",
            "name": "nostr",
            "summary": "",
            "url": "namespaces/swentel-nostr.html"
        },                {
            "fqsen": "\\swentel",
            "name": "swentel",
            "summary": "",
            "url": "namespaces/swentel.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Event",
            "name": "Event",
            "summary": "",
            "url": "namespaces/swentel-nostr-event.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Examples",
            "name": "Examples",
            "summary": "",
            "url": "namespaces/swentel-nostr-examples.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Key",
            "name": "Key",
            "summary": "",
            "url": "namespaces/swentel-nostr-key.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Message",
            "name": "Message",
            "summary": "",
            "url": "namespaces/swentel-nostr-message.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Relay",
            "name": "Relay",
            "summary": "",
            "url": "namespaces/swentel-nostr-relay.html"
        },                {
            "fqsen": "\\swentel\\nostr\\Sign",
            "name": "Sign",
            "summary": "",
            "url": "namespaces/swentel-nostr-sign.html"
        }            ]
);
